on:
  push:
    branches:
    - main
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
     steps:
    - uses: actions/checkout@v4
     - name: npm install, build and test
     run : |
         echo "Welcome to the Git actions"
         echo "This is Guna "
         echo "Testing workflows"
         
